### ISSUE TITLE
Update the k3s.io site as per CNCF website guidelines

### ISSUE THREAD

**Issue by davidnuzik** [rancherlabs/k3s-website#54]
I'd like to request the following changes as per the https://github.com/cncf/foundation/blob/master/website-guidelines.md
These changes are required in order to complete the [k3s project onboarding](https://github.com/cncf/toc/issues/513).

Add a section just above the footer indicating the following as per guideline number 6.
> “We are a Cloud Native Computing Foundation sandbox project.” and the CNCF logo.

In the footer, update the copyright as per guideline number 7.
> 2020 © K3s Project Authors. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page: https://www.linuxfoundation.org/trademark-usage

Below you will find an edited image of a screenshot from https://www.envoyproxy.io/ which has a good example of this. I have plugged in the words that need changing from their example and outlined what needs to be done inside the orange boxes. Should you have any questions, please do not hesitate to ask.

![image](https://user-images.githubusercontent.com/45179589/96518028-d235eb80-121e-11eb-8d79-aa0a3b44d140.png)

**Comment by jrcreative** [comment]
@davidnuzik Here's a screenshot of what I have locally. I think it's solid. My only question would be about the links to other projects. Does that violate CNCF guidelines, or is it fine since they're all open source projects?
![Uploading Screen Shot 2020-10-29 at 2.05.27 PM.png…]()

**Comment by davidnuzik** [comment]
@jrcreative this LGTM. Yeah I can understand the concern on the links. My take on that was it's fine - they just don't want us linking to forms such as for capturing leads. #4 on the list should be okay too.

Let's ship it :) If we need changes later (not likely I think) we can do this separately later as lower priority.
