### ISSUE TITLE
Remove Rancher header from the website

### ISSUE THREAD

**Issue by davidnuzik** [rancherlabs/k3s-website#59]
CNCF would like to see the Rancher header removed from the k3s.io website.

- Remove rancher-header div completely.

![image](https://user-images.githubusercontent.com/45179589/100672027-92cee480-331e-11eb-9e2c-dee24f0ef301.png)

**Comment by jrcreative** [comment]
np @davidnuzik, is there any value in moving the star ratings and fork widgets?

**Comment by davidnuzik** [comment]
@jrcreative thanks for asking. I think at present, no. I think we should go ahead and remove the whole header including star rating and forks (widgets). CNCF has useful statistics and likely they would instead want a link to that. We can consider this later as a low priority thing.

**Comment by davidnuzik** [comment]
Thanks @jrcreative 
Closing. The PR has merged. It will be a bit until the update is live.
